# load Dataset

In [2]:
import pandas as pd 
df1= pd.read_csv("student-scores.csv")
df=df1.copy()
df.head

<bound method NDFrame.head of         id first_name last_name                                    email  \
0        1       Paul     Casey           paul.casey.1@gslingacademy.com
1        2   Danielle  Sandoval    danielle.sandoval.2@gslingacademy.com
2        3       Tina   Andrews         tina.andrews.3@gslingacademy.com
3        4       Tara     Clark           tara.clark.4@gslingacademy.com
4        5    Anthony    Campos       anthony.campos.5@gslingacademy.com
...    ...        ...       ...                                      ...
1995  1996       Alan  Reynolds     alan.reynolds.1996@gslingacademy.com
1996  1997     Thomas   Gilbert    thomas.gilbert.1997@gslingacademy.com
1997  1998    Madison     Cross     madison.cross.1998@gslingacademy.com
1998  1999   Brittany   Compton  brittany.compton.1999@gslingacademy.com
1999  2000    Natalie     Smith     natalie.smith.2000@gslingacademy.com

      gender  part_time_job  absence_days  extracurricular_activities  \
0       male          False             3                       False
1     female          False             2                       False
2     female          False             9                        True
3     female          False             5                       False
4       male          False             5                       False
...      ...            ...           ...                         ...
1995    male          False             2                       False
1996    male          False             2                       False
1997  female          False             5                       False
1998  female           True            10                        True
1999  female          False             5                       False

      weekly_self_study_hours      career_aspiration  math_score  \
0                          27                 Lawyer          73
1                          47                 Doctor          90
2                          13     Government Officer          81
3                           3                 Artist          71
4                          10                Unknown          84
...                       ...                    ...         ...
1995                       30  Construction Engineer          83
1996                       20      Software Engineer          89
1997                       14      Software Engineer          97
1998                        5         Business Owner          51
1999                       27             Accountant          82

      history_score  physics_score  chemistry_score  biology_score  \
0                81             93               97             63
1                86             96              100             90
2                97             95               96             65
3                74             88               80             89
4                77             65               65             80
...             ...            ...              ...            ...
1995             77             84               73             75
1996             65             73               80             87
1997             85             63               93             68
1998             96             72               89             95
1999             99             91               69             83

      english_score  geography_score
0                80               87
1                88               90
2                77               94
3                63               86
4                74               76
...             ...              ...
1995             84               82
1996             67               73
1997             94               78
1998             88               75
1999             93              100

[2000 rows x 17 columns]>

# drop irrelevant columns

In [3]:
df.drop(columns=['id','first_name','last_name','email'],axis=1,inplace=True)
df.columns

Index(['gender', 'part_time_job', 'absence_days', 'extracurricular_activities',
       'weekly_self_study_hours', 'career_aspiration', 'math_score',
       'history_score', 'physics_score', 'chemistry_score', 'biology_score',
       'english_score', 'geography_score'],
      dtype='object')

In [4]:
df

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82
1996,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73
1997,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78
1998,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75
1999,female,False,5,False,27,Accountant,82,99,91,69,83,93,100

# create new features from all scores like total-score and average score

In [5]:
df["total_score"]=df["math_score"]+df["history_score"]+df["physics_score"]+df["chemistry_score"]+df["biology_score"]
df["average_score"]=df["total_score"]/7
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,407,58.142857
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,462,66.000000
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,434,62.000000
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86,402,57.428571
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,371,53.000000

In [6]:
df['career_aspiration'].value_counts()

career_aspiration
Software Engineer        315
Business Owner           309
Unknown                  223
Banker                   169
Lawyer                   138
Accountant               126
Doctor                   119
Real Estate Developer     83
Stock Investor            73
Construction Engineer     68
Artist                    67
Game Developer            63
Government Officer        61
Teacher                   59
Designer                  56
Scientist                 39
Writer                    32
Name: count, dtype: int64

In [7]:
len(df['career_aspiration'].unique())

17

# encoding categorial columns

In [8]:
df

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,407,58.142857
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,462,66.000000
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,434,62.000000
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86,402,57.428571
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,371,53.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82,392,56.000000
1996,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73,394,56.285714
1997,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78,406,58.000000
1998,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75,403,57.571429
1999,female,False,5,False,27,Accountant,82,99,91,69,83,93,100,424,60.571429

In [9]:
gender_map = {'male': 0, 'female': 1}
part_time_job_map = {False: 0, True: 1}
extracurricular_activities_map = {False: 0, True: 1}
career_aspiration_map = {
        'Lawyer': 0, 'Doctor': 1, 'Government Officer': 2, 'Artist': 3, 'Unknown': 4,
        'Software Engineer': 5, 'Teacher': 6, 'Business Owner': 7, 'Scientist': 8,
        'Banker': 9, 'Writer': 10, 'Accountant': 11, 'Designer': 12,
        'Construction Engineer': 13, 'Game Developer': 14, 'Stock Investor': 15,
        'Real Estate Developer': 16
    }
# Apply mapping to the DataFrame
df['gender'] = df['gender'].map(gender_map)
df['part_time_job'] = df['part_time_job'].map(part_time_job_map)
df['extracurricular_activities'] = df['extracurricular_activities'].map(extracurricular_activities_map)
df['career_aspiration'] = df['career_aspiration'].map(career_aspiration_map)

In [10]:
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,0,0,3,0,27,0,73,81,93,97,63,80,87,407,58.142857
1,1,0,2,0,47,1,90,86,96,100,90,88,90,462,66.000000
2,1,0,9,1,13,2,81,97,95,96,65,77,94,434,62.000000
3,1,0,5,0,3,3,71,74,88,80,89,63,86,402,57.428571
4,0,0,5,0,10,4,84,77,65,65,80,74,76,371,53.000000

In [11]:
df

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
0,0,0,3,0,27,0,73,81,93,97,63,80,87,407,58.142857
1,1,0,2,0,47,1,90,86,96,100,90,88,90,462,66.000000
2,1,0,9,1,13,2,81,97,95,96,65,77,94,434,62.000000
3,1,0,5,0,3,3,71,74,88,80,89,63,86,402,57.428571
4,0,0,5,0,10,4,84,77,65,65,80,74,76,371,53.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,2,0,30,13,83,77,84,73,75,84,82,392,56.000000
1996,0,0,2,0,20,5,89,65,73,80,87,67,73,394,56.285714
1997,1,0,5,0,14,5,97,85,63,93,68,94,78,406,58.000000
1998,1,1,10,1,5,7,51,96,72,89,95,88,75,403,57.571429
1999,1,0,5,0,27,11,82,99,91,69,83,93,100,424,60.571429

# Balance dataset

In [12]:
df['career_aspiration'].value_counts()

career_aspiration
5     315
7     309
4     223
9     169
0     138
11    126
1     119
16     83
15     73
13     68
3      67
14     63
2      61
6      59
12     56
8      39
10     32
Name: count, dtype: int64

In [13]:
pip install imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.12.3-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: numpy>=1.17.3 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (1.12.0)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (1.4.1.post1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (3.4.0)
Downloading imbalanced_learn-0.12.3-py3-none-any.whl (258 kB)
Installing collected packages: imbalanced-learn
Successfully installed imbalanced-learn-0.12.3
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)

In [14]:
!pip install imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imbalanced-learn in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (0.12.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (1.12.0)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (1.4.1.post1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from imbalanced-learn) (3.4.0)

WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)

In [15]:
from imblearn.over_sampling import SMOTE

# Create SMOTE object
smote = SMOTE(random_state=42)

# Separate features and target variable
X = df.drop('career_aspiration', axis=1)
y = df['career_aspiration']

# Apply SMOTE to the data
X_resampled, y_resampled = smote.fit_resample(X, y)

In [16]:
y_resampled.value_counts()

career_aspiration
0     315
9     315
15    315
14    315
13    315
12    315
11    315
10    315
8     315
1     315
7     315
6     315
5     315
4     315
3     315
2     315
16    315
Name: count, dtype: int64

In [17]:
y_resampled.shape

(5355,)

# Train test Split

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2, random_state=42)

In [19]:
X_train.shape,y_train.shape,X_test.shape ,y_test.shape

((4284, 14), (4284,), (1071, 14), (1071,))

# Feature Scalling

In [20]:
X_train

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,average_score
2369,0,0,4,0,40,95,94,94,89,85,85,89,458,65.508543
3955,0,0,1,0,15,88,67,90,88,48,85,62,384,54.867941
3785,1,0,1,0,16,71,99,98,95,91,95,95,456,65.181904
120,1,1,0,0,13,66,90,83,80,76,90,91,395,56.428571
3699,1,0,3,0,21,68,77,82,92,92,90,71,413,59.025673
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3092,1,0,1,0,11,61,77,93,64,90,91,87,387,55.352344
3772,0,0,1,0,31,65,88,70,71,73,96,64,368,52.688670
5191,0,0,4,0,4,86,77,64,84,83,93,80,396,56.584340
5226,0,0,2,0,4,74,90,67,85,81,71,87,400,57.145786
860,0,0,4,0,25,100,62,78,74,72,73,78,386,55.142857

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [22]:
X_train_scaled.shape

(4284, 14)

In [23]:
X_train_scaled

array([[-0.77170637, -0.25729767,  0.46303816, ...,  0.74466033,
         1.54813252,  1.5551114 ],
       [-0.77170637, -0.25729767, -0.92316412, ..., -1.7968218 ,
        -0.8046697 , -0.8109445 ],
       [ 1.29582965, -0.25729767, -0.92316412, ...,  1.30943413,
         1.48454327,  1.48247967],
       ...,
       [-0.77170637, -0.25729767,  0.46303816, ..., -0.10250038,
        -0.4231342 , -0.42928431],
       [-0.77170637, -0.25729767, -0.4610967 , ...,  0.55640239,
        -0.29595571, -0.30444056],
       [-0.77170637, -0.25729767,  0.46303816, ..., -0.29075832,
        -0.74108045, -0.74981395]])

# Model training Multiple model

In [24]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-2.1.1-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\akshada mane\appdata\roaming\python\python312\site-packages (from xgboost) (1.12.0)
Downloading xgboost-2.1.1-py3-none-win_amd64.whl (124.9 MB)
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/124.9 MB 4.2 MB/s eta 0:00:30
    --------------------------------------- 1.6/124.9 MB 4.4 MB/s eta 0:00:28
    --------------------------------------- 1.8/124.9 MB 3.2 MB/s eta 0:00:38
    --------------------------------------- 2.1/124.9 MB 2.8 MB/s eta 0:00:44
    --------------------------------------- 2.6/124.9 MB 2.9 MB/s eta 0:00:43
   - -------------------------------------- 3.1/124.9 MB 2.6 MB/s eta 0:00:47
   - -------------------------------------- 3.9/124.9 MB 2.8 MB/s eta 0:00:44
   - -------------------------------------- 4.2/124.9 MB 2.6 MB/s eta 0:00:48
   - -------------------------------------- 4.5/124.9 MB 2.5 MB/s eta 0:00:49
   - -------------------------------------- 4.7/124.9 MB 2.3 MB/s eta 0:00:52
   - -------------------------------------- 5.2/124.9 MB 2.3 MB/s eta 0:00:52
   - -------------------------------------- 5.5/124.9 MB 2.3 MB/s eta 0:00:53
   - -------------------------------------- 6.0/124.9 MB 2.2 MB/s eta 0:00:54
   -- ------------------------------------- 6.6/124.9 MB 2.2 MB/s eta 0:00:53
   -- ------------------------------------- 7.1/124.9 MB 2.3 MB/s eta 0:00:53
   -- ------------------------------------- 7.3/124.9 MB 2.3 MB/s eta 0:00:52
   -- ------------------------------------- 7.9/124.9 MB 2.2 MB/s eta 0:00:54
   -- ------------------------------------- 8.1/124.9 MB 2.2 MB/s eta 0:00:53
   -- ------------------------------------- 8.4/124.9 MB 2.1 MB/s eta 0:00:56
   -- ------------------------------------- 8.7/124.9 MB 2.1 MB/s eta 0:00:56
   -- ------------------------------------- 9.2/124.9 MB 2.1 MB/s eta 0:00:56
   --- ------------------------------------ 9.7/124.9 MB 2.1 MB/s eta 0:00:55
   --- ------------------------------------ 10.2/124.9 MB 2.1 MB/s eta 0:00:55
   --- ------------------------------------ 10.5/124.9 MB 2.1 MB/s eta 0:00:54
   --- ------------------------------------ 11.0/124.9 MB 2.1 MB/s eta 0:00:54
   --- ------------------------------------ 11.5/124.9 MB 2.1 MB/s eta 0:00:54
   --- ------------------------------------ 11.8/124.9 MB 2.1 MB/s eta 0:00:55
   --- ------------------------------------ 12.1/124.9 MB 2.1 MB/s eta 0:00:55
   ---- ----------------------------------- 12.8/124.9 MB 2.1 MB/s eta 0:00:54
   ---- ----------------------------------- 13.4/124.9 MB 2.1 MB/s eta 0:00:53
   ---- ----------------------------------- 13.9/124.9 MB 2.1 MB/s eta 0:00:53
   ---- ----------------------------------- 14.4/124.9 MB 2.1 MB/s eta 0:00:52
   ---- ----------------------------------- 14.9/124.9 MB 2.1 MB/s eta 0:00:52
   ----- ---------------------------------- 15.7/124.9 MB 2.2 MB/s eta 0:00:51
   ----- ---------------------------------- 16.0/124.9 MB 2.2 MB/s eta 0:00:50
   ----- ---------------------------------- 16.3/124.9 MB 2.2 MB/s eta 0:00:50
   ----- ---------------------------------- 17.0/124.9 MB 2.2 MB/s eta 0:00:50
   ----- ---------------------------------- 17.6/124.9 MB 2.2 MB/s eta 0:00:49
   ----- ---------------------------------- 18.1/124.9 MB 2.2 MB/s eta 0:00:49
   ------ --------------------------------- 18.9/124.9 MB 2.2 MB/s eta 0:00:48
   ------ --------------------------------- 19.4/124.9 MB 2.2 MB/s eta 0:00:48
   ------ --------------------------------- 19.7/124.9 MB 2.2 MB/s eta 0:00:47
   ------ --------------------------------- 19.9/124.9 MB 2.2 MB/s eta 0:00:48
   ------ --------------------------------- 20.2/124.9 MB 2.2 MB/s eta 0:00:48
   ------ --------------------------------- 20.7/124.9 MB 2.2 MB/s eta 0:00:48
   ------ --------------------------------- 21.0/124.9 MB 2.2 MB/s eta 0:00:48
   ------ --------------------------------- 21.5/124.9 MB 2.2 MB/s eta 0:00:48
   ------- -------------------------------- 22.0/124.9 MB 2.2 MB/s eta 0:00:48
   ------- -------------------------------- 22.5/124.9 MB 2.2 MB/s eta 0:00:47
   ------- -------------------------------- 23.1/124.9 MB 2.2 MB/s eta 0:00:47
   ------- -------------------------------- 23.6/124.9 MB 2.2 MB/s eta 0:00:47
   ------- -------------------------------- 24.1/124.9 MB 2.2 MB/s eta 0:00:46
   ------- -------------------------------- 24.6/124.9 MB 2.2 MB/s eta 0:00:46
   -------- ------------------------------- 25.4/124.9 MB 2.2 MB/s eta 0:00:45
   -------- ------------------------------- 26.0/124.9 MB 2.2 MB/s eta 0:00:45
   -------- ------------------------------- 26.5/124.9 MB 2.2 MB/s eta 0:00:44
   -------- ------------------------------- 27.0/124.9 MB 2.2 MB/s eta 0:00:44
   -------- ------------------------------- 27.5/124.9 MB 2.2 MB/s eta 0:00:44
   -------- ------------------------------- 28.0/124.9 MB 2.3 MB/s eta 0:00:43
   --------- ------------------------------ 28.6/124.9 MB 2.3 MB/s eta 0:00:43
   --------- ------------------------------ 29.1/124.9 MB 2.3 MB/s eta 0:00:43
   --------- ------------------------------ 29.6/124.9 MB 2.3 MB/s eta 0:00:43
   --------- ------------------------------ 30.1/124.9 MB 2.3 MB/s eta 0:00:42
   --------- ------------------------------ 30.7/124.9 MB 2.3 MB/s eta 0:00:42
   ---------- ----------------------------- 31.5/124.9 MB 2.3 MB/s eta 0:00:41
   ---------- ----------------------------- 32.0/124.9 MB 2.3 MB/s eta 0:00:41
   ---------- ----------------------------- 32.2/124.9 MB 2.3 MB/s eta 0:00:41
   ---------- ----------------------------- 32.8/124.9 MB 2.3 MB/s eta 0:00:41
   ---------- ----------------------------- 33.0/124.9 MB 2.3 MB/s eta 0:00:41
   ---------- ----------------------------- 33.6/124.9 MB 2.3 MB/s eta 0:00:41
   ---------- ----------------------------- 33.8/124.9 MB 2.3 MB/s eta 0:00:40
   ----------- ---------------------------- 34.6/124.9 MB 2.3 MB/s eta 0:00:40
   ----------- ---------------------------- 35.1/124.9 MB 2.3 MB/s eta 0:00:40
   ----------- ---------------------------- 35.7/124.9 MB 2.3 MB/s eta 0:00:39
   ----------- ---------------------------- 36.4/124.9 MB 2.3 MB/s eta 0:00:39
   ----------- ---------------------------- 37.0/124.9 MB 2.3 MB/s eta 0:00:39
   ----------- ---------------------------- 37.2/124.9 MB 2.3 MB/s eta 0:00:38
   ------------ --------------------------- 37.5/124.9 MB 2.3 MB/s eta 0:00:38
   ------------ --------------------------- 38.0/124.9 MB 2.3 MB/s eta 0:00:38
   ------------ --------------------------- 38.3/124.9 MB 2.3 MB/s eta 0:00:38
   ------------ --------------------------- 38.8/124.9 MB 2.3 MB/s eta 0:00:38
   ------------ --------------------------- 39.1/124.9 MB 2.3 MB/s eta 0:00:38
   ------------ --------------------------- 39.3/124.9 MB 2.3 MB/s eta 0:00:38
   ------------ --------------------------- 39.8/124.9 MB 2.3 MB/s eta 0:00:38
   ------------- -------------------------- 40.6/124.9 MB 2.3 MB/s eta 0:00:38
   ------------- -------------------------- 41.2/124.9 MB 2.3 MB/s eta 0:00:37
   ------------- -------------------------- 41.4/124.9 MB 2.3 MB/s eta 0:00:37
   ------------- -------------------------- 42.2/124.9 MB 2.3 MB/s eta 0:00:37
   ------------- -------------------------- 42.7/124.9 MB 2.3 MB/s eta 0:00:36
   ------------- -------------------------- 43.3/124.9 MB 2.3 MB/s eta 0:00:36
   -------------- ------------------------- 44.0/124.9 MB 2.3 MB/s eta 0:00:36
   -------------- ------------------------- 44.6/124.9 MB 2.3 MB/s eta 0:00:35
   -------------- ------------------------- 45.1/124.9 MB 2.3 MB/s eta 0:00:35
   -------------- ------------------------- 45.4/124.9 MB 2.3 MB/s eta 0:00:35
   -------------- ------------------------- 45.9/124.9 MB 2.3 MB/s eta 0:00:35
   -------------- ------------------------- 46.7/124.9 MB 2.3 MB/s eta 0:00:34
   --------------- ------------------------ 47.4/124.9 MB 2.3 MB/s eta 0:00:34
   --------------- ------------------------ 48.0/124.9 MB 2.3 MB/s eta 0:00:34
   --------------- ------------------------ 48.5/124.9 MB 2.3 MB/s eta 0:00:33
   --------------- ------------------------ 49.0/124.9 MB 2.3 MB/s eta 0:00:33
   --------------- ------------------------ 49.8/124.9 MB 2.3 MB/s eta 0:00:33
   ---------------- ----------------------- 50.3/124.9 MB 2.3 MB/s eta 0:00:32
   ---------------- ----------------------- 50.3/124.9 MB 2.3 MB/s eta 0:00:32
   ---------------- ----------------------- 50.3/124.9 MB 2.3 MB/s eta 0:00:32
   ---------------- ----------------------- 50.9/124.9 MB 2.3 MB/s eta 0:00:33
   ---------------- ----------------------- 51.1/124.9 MB 2.3 MB/s eta 0:00:33
   ---------------- ----------------------- 51.4/124.9 MB 2.3 MB/s eta 0:00:33
   ---------------- ----------------------- 51.9/124.9 MB 2.3 MB/s eta 0:00:33
   ---------------- ----------------------- 52.2/124.9 MB 2.3 MB/s eta 0:00:32
   ---------------- ----------------------- 52.7/124.9 MB 2.3 MB/s eta 0:00:32
   ----------------- ---------------------- 53.2/124.9 MB 2.3 MB/s eta 0:00:32
   ----------------- ---------------------- 54.0/124.9 MB 2.3 MB/s eta 0:00:32
   ----------------- ---------------------- 54.3/124.9 MB 2.3 MB/s eta 0:00:31
   ----------------- ---------------------- 54.5/124.9 MB 2.3 MB/s eta 0:00:31
   ----------------- ---------------------- 55.1/124.9 MB 2.3 MB/s eta 0:00:31
   ----------------- ---------------------- 55.6/124.9 MB 2.3 MB/s eta 0:00:31
   ------------------ --------------------- 56.4/124.9 MB 2.3 MB/s eta 0:00:31
   ------------------ --------------------- 56.9/124.9 MB 2.3 MB/s eta 0:00:30
   ------------------ --------------------- 57.4/124.9 MB 2.3 MB/s eta 0:00:30
   ------------------ --------------------- 57.9/124.9 MB 2.3 MB/s eta 0:00:30
   ------------------ --------------------- 58.5/124.9 MB 2.3 MB/s eta 0:00:29
   ------------------ --------------------- 59.2/124.9 MB 2.3 MB/s eta 0:00:29
   ------------------- -------------------- 59.8/124.9 MB 2.3 MB/s eta 0:00:29
   ------------------- -------------------- 60.3/124.9 MB 2.3 MB/s eta 0:00:29
   ------------------- -------------------- 60.8/124.9 MB 2.3 MB/s eta 0:00:28
   ------------------- -------------------- 61.6/124.9 MB 2.3 MB/s eta 0:00:28
   ------------------- -------------------- 62.1/124.9 MB 2.3 MB/s eta 0:00:27
   -------------------- ------------------- 62.7/124.9 MB 2.3 MB/s eta 0:00:27
   -------------------- ------------------- 63.4/124.9 MB 2.3 MB/s eta 0:00:27
   -------------------- ------------------- 64.0/124.9 MB 2.3 MB/s eta 0:00:27
   -------------------- ------------------- 64.5/124.9 MB 2.3 MB/s eta 0:00:26
   -------------------- ------------------- 65.3/124.9 MB 2.4 MB/s eta 0:00:26
   --------------------- ------------------ 65.8/124.9 MB 2.4 MB/s eta 0:00:26
   --------------------- ------------------ 66.3/124.9 MB 2.3 MB/s eta 0:00:25
   --------------------- ------------------ 66.8/124.9 MB 2.4 MB/s eta 0:00:25
   --------------------- ------------------ 67.4/124.9 MB 2.4 MB/s eta 0:00:25
   --------------------- ------------------ 67.9/124.9 MB 2.4 MB/s eta 0:00:25
   --------------------- ------------------ 68.7/124.9 MB 2.4 MB/s eta 0:00:24
   ---------------------- ----------------- 69.5/124.9 MB 2.4 MB/s eta 0:00:24
   ---------------------- ----------------- 70.0/124.9 MB 2.4 MB/s eta 0:00:24
   ---------------------- ----------------- 70.8/124.9 MB 2.4 MB/s eta 0:00:23
   ---------------------- ----------------- 71.6/124.9 MB 2.4 MB/s eta 0:00:23
   ----------------------- ---------------- 72.4/124.9 MB 2.4 MB/s eta 0:00:23
   ----------------------- ---------------- 73.1/124.9 MB 2.4 MB/s eta 0:00:22
   ----------------------- ---------------- 73.9/124.9 MB 2.4 MB/s eta 0:00:22
   ----------------------- ---------------- 74.7/124.9 MB 2.4 MB/s eta 0:00:21
   ------------------------ --------------- 75.2/124.9 MB 2.4 MB/s eta 0:00:21
   ------------------------ --------------- 75.2/124.9 MB 2.4 MB/s eta 0:00:21
   ------------------------ --------------- 75.8/124.9 MB 2.4 MB/s eta 0:00:21
   ------------------------ --------------- 76.0/124.9 MB 2.4 MB/s eta 0:00:21
   ------------------------ --------------- 76.5/124.9 MB 2.4 MB/s eta 0:00:21
   ------------------------ --------------- 77.1/124.9 MB 2.4 MB/s eta 0:00:20
   ------------------------ --------------- 77.6/124.9 MB 2.4 MB/s eta 0:00:20
   ------------------------- -------------- 78.4/124.9 MB 2.4 MB/s eta 0:00:20
   ------------------------- -------------- 79.4/124.9 MB 2.4 MB/s eta 0:00:19
   ------------------------- -------------- 80.2/124.9 MB 2.5 MB/s eta 0:00:19
   ------------------------- -------------- 81.0/124.9 MB 2.5 MB/s eta 0:00:18
   -------------------------- ------------- 81.5/124.9 MB 2.5 MB/s eta 0:00:18
   -------------------------- ------------- 82.1/124.9 MB 2.5 MB/s eta 0:00:18
   -------------------------- ------------- 82.8/124.9 MB 2.5 MB/s eta 0:00:17
   -------------------------- ------------- 83.6/124.9 MB 2.5 MB/s eta 0:00:17
   --------------------------- ------------ 84.4/124.9 MB 2.5 MB/s eta 0:00:17
   --------------------------- ------------ 85.2/124.9 MB 2.5 MB/s eta 0:00:16
   --------------------------- ------------ 86.0/124.9 MB 2.5 MB/s eta 0:00:16
   --------------------------- ------------ 86.8/124.9 MB 2.5 MB/s eta 0:00:15
   ---------------------------- ----------- 87.6/124.9 MB 2.6 MB/s eta 0:00:15
   ---------------------------- ----------- 88.3/124.9 MB 2.6 MB/s eta 0:00:15
   ---------------------------- ----------- 89.4/124.9 MB 2.6 MB/s eta 0:00:14
   ---------------------------- ----------- 90.2/124.9 MB 2.6 MB/s eta 0:00:14
   ----------------------------- ---------- 90.7/124.9 MB 2.6 MB/s eta 0:00:14
   ----------------------------- ---------- 91.0/124.9 MB 2.6 MB/s eta 0:00:14
   ----------------------------- ---------- 91.5/124.9 MB 2.6 MB/s eta 0:00:13
   ----------------------------- ---------- 92.0/124.9 MB 2.6 MB/s eta 0:00:13
   ----------------------------- ---------- 92.5/124.9 MB 2.6 MB/s eta 0:00:13
   ----------------------------- ---------- 93.3/124.9 MB 2.6 MB/s eta 0:00:13
   ----------------------------- ---------- 93.6/124.9 MB 2.6 MB/s eta 0:00:13
   ------------------------------ --------- 94.1/124.9 MB 2.6 MB/s eta 0:00:12
   ------------------------------ --------- 94.9/124.9 MB 2.6 MB/s eta 0:00:12
   ------------------------------ --------- 95.4/124.9 MB 2.6 MB/s eta 0:00:12
   ------------------------------ --------- 96.2/124.9 MB 2.6 MB/s eta 0:00:12
   ------------------------------- -------- 97.0/124.9 MB 2.6 MB/s eta 0:00:11
   ------------------------------- -------- 97.5/124.9 MB 2.6 MB/s eta 0:00:11
   ------------------------------- -------- 98.0/124.9 MB 2.6 MB/s eta 0:00:11
   ------------------------------- -------- 98.8/124.9 MB 2.6 MB/s eta 0:00:10
   ------------------------------- -------- 99.6/124.9 MB 2.7 MB/s eta 0:00:10
   -------------------------------- ------- 100.1/124.9 MB 2.7 MB/s eta 0:00:10
   -------------------------------- ------- 100.9/124.9 MB 2.7 MB/s eta 0:00:09
   -------------------------------- ------- 101.7/124.9 MB 2.7 MB/s eta 0:00:09
   -------------------------------- ------- 102.5/124.9 MB 2.7 MB/s eta 0:00:09
   --------------------------------- ------ 103.3/124.9 MB 2.7 MB/s eta 0:00:08
   --------------------------------- ------ 104.1/124.9 MB 2.7 MB/s eta 0:00:08
   --------------------------------- ------ 104.9/124.9 MB 2.7 MB/s eta 0:00:08
   --------------------------------- ------ 105.6/124.9 MB 2.7 MB/s eta 0:00:08
   ---------------------------------- ----- 106.2/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 106.4/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 107.2/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 107.7/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 108.3/124.9 MB 2.7 MB/s eta 0:00:07
   ---------------------------------- ----- 109.1/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 109.6/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 110.4/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 110.9/124.9 MB 2.7 MB/s eta 0:00:06
   ----------------------------------- ---- 111.7/124.9 MB 2.7 MB/s eta 0:00:05
   ------------------------------------ --- 112.5/124.9 MB 2.8 MB/s eta 0:00:05
   ------------------------------------ --- 113.2/124.9 MB 2.8 MB/s eta 0:00:05
   ------------------------------------ --- 113.8/124.9 MB 2.8 MB/s eta 0:00:05
   ------------------------------------ --- 114.6/124.9 MB 2.8 MB/s eta 0:00:04
   ------------------------------------ --- 115.1/124.9 MB 2.8 MB/s eta 0:00:04
   ------------------------------------- -- 115.9/124.9 MB 2.8 MB/s eta 0:00:04
   ------------------------------------- -- 116.7/124.9 MB 2.8 MB/s eta 0:00:03
   ------------------------------------- -- 117.4/124.9 MB 2.8 MB/s eta 0:00:03
   ------------------------------------- -- 118.2/124.9 MB 2.8 MB/s eta 0:00:03
   -------------------------------------- - 119.3/124.9 MB 2.8 MB/s eta 0:00:02
   -------------------------------------- - 119.5/124.9 MB 2.8 MB/s eta 0:00:02
   -------------------------------------- - 120.1/124.9 MB 2.8 MB/s eta 0:00:02
   -------------------------------------- - 120.8/124.9 MB 2.8 MB/s eta 0:00:02
   -------------------------------------- - 121.6/124.9 MB 2.8 MB/s eta 0:00:02
   ---------------------------------------  122.4/124.9 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  123.2/124.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  124.0/124.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  124.5/124.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  124.8/124.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  124.8/124.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 124.9/124.9 MB 2.9 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-2.1.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Akshada Mane\AppData\Roaming\Python\Python312\site-packages)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier": SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

# Train and evaluate each model
for name, model in models.items():
    print("="*50)
    print("Model:", name)
    # Train the model
    model.fit(X_train_scaled, y_train)
    
    # Predict on test set
    y_pred = model.predict(X_test_scaled)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print metrics
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)

==================================================
Model: Logistic Regression
Accuracy: 0.480859010270775
Classification Report:
               precision    recall  f1-score   support

           0       0.41      0.51      0.46        68
           1       0.50      0.65      0.57        72
           2       0.47      0.51      0.49        57
           3       0.49      0.53      0.51        58
           4       0.24      0.14      0.17        66
           5       0.34      0.28      0.31        76
           6       0.59      0.92      0.72        71
           7       0.86      0.90      0.88        61
           8       0.46      0.49      0.47        53
           9       0.19      0.07      0.10        61
          10       0.59      0.71      0.65        63
          11       0.45      0.43      0.44        53
          12       0.37      0.21      0.26        68
          13       0.31      0.49      0.38        55
          14       0.59      0.95      0.73        57
          15       0.33      0.19      0.24        63
          16       0.46      0.26      0.33        69

    accuracy                           0.48      1071
   macro avg       0.45      0.48      0.45      1071
weighted avg       0.45      0.48      0.45      1071

Confusion Matrix:
 [[35  4  0  0  0  7  0  0  3  1  9  0  0  7  0  2  0]
 [ 2 47  0  0  0  4  0  0 12  0  0  0  0  7  0  0  0]
 [ 0  0 29  1  0  1  5  0  0  0  2  0  6  1  3  3  6]
 [ 0  0  3 31  0  0  2  1  0  0  0  0  0  0 11  0 10]
 [ 6  5  6  3  9  7  5  1  4  4  0  2  6  4  2  1  1]
 [ 9  8  0  0  1 21  1  0  2  6  1  7  2 14  0  4  0]
 [ 0  0  0  0  1  0 65  0  0  1  2  0  0  0  2  0  0]
 [ 0  0  0  3  0  0  0 55  0  0  0  0  0  0  3  0  0]
 [ 4 15  0  0  0  1  0  0 26  0  6  0  0  0  0  1  0]
 [11  2  0  0  3  9  8  0  1  4  3  5  7  6  0  2  0]
 [ 6  3  0  0  0  0  3  0  1  1 45  0  1  2  1  0  0]
 [ 0  2  0  0  4  6  3  0  2  1  0 23  0  6  0  6  0]
 [ 3  2  7  4  6  1 12  0  2  0  4  0 14  5  3  3  2]
 [ 4  3  1  0  5  0  0  0  4  2  2  4  1 27  0  2  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0 54  0  0]
 [ 5  3  5  0  8  3  1  1  0  1  1 10  1  7  3 12  2]
 [ 0  0 11 18  0  1  5  6  0  0  1  0  0  0  9  0 18]]
==================================================
Model: Support Vector Classifier
Accuracy: 0.6349206349206349
Classification Report:
               precision    recall  f1-score   support

           0       0.53      0.62      0.57        68
           1       0.58      0.86      0.69        72
           2       0.59      0.79      0.68        57
           3       0.67      0.71      0.69        58
           4       0.42      0.12      0.19        66
           5       0.44      0.32      0.37        76
           6       0.73      0.93      0.82        71
           7       0.84      0.93      0.88        61
           8       0.66      0.81      0.73        53
           9       0.38      0.33      0.35        61
          10       0.84      0.90      0.87        63
          11       0.78      0.40      0.53        53
          12       0.56      0.46      0.50        68
          13       0.53      0.82      0.64        55
          14       0.73      0.95      0.82        57
          15       0.65      0.44      0.53        63
          16       0.80      0.52      0.63        69

    accuracy                           0.63      1071
   macro avg       0.63      0.64      0.62      1071
weighted avg       0.63      0.63      0.61      1071

Confusion Matrix:
 [[42  4  0  0  0  4  0  0  4  3  7  1  0  2  0  1  0]
 [ 1 62  0  0  0  1  0  0  5  0  0  0  0  3  0  0  0]
 [ 0  1 45  2  1  0  2  0  0  0  1  0  2  1  0  1  1]
 [ 0  0  3 41  1  0  1  1  0  1  0  0  0  0  9  0  1]
 [ 6  8  7  1  8  6  2  2  1  7  0  4  7  4  1  2  0]
 [11  9  1  0  0 24  1  1  4 10  0  0  2 11  0  2  0]
 [ 0  0  1  0  0  0 66  0  0  1  1  0  1  0  0  0  1]
 [ 0  0  0  2  0  0  0 57  0  0  0  0  0  0  1  0  1]
 [ 1  8  0  0  0  1  0  0 43  0  0  0  0  0  0  0  0]
 [ 7  2  0  0  0  8  5  1  2 20  0  0  5  8  0  3  0]
 [ 0  2  2  0  0  0  0  0  0  2 57  0  0  0  0  0  0]
 [ 2  3  1  0  3  5  0  1  4  4  1 21  3  1  0  4  0]
 [ 5  3  5  0  3  0  9  0  0  0  1  0 31  4  2  1  4]
 [ 1  2  0  0  1  0  0  0  2  2  0  0  1 45  0  1  0]
 [ 0  0  0  0  0  0  0  2  0  0  0  0  1  0 54  0  0]
 [ 4  3  4  1  2  5  1  0  0  3  0  1  2  6  2 28  1]
 [ 0  0  7 14  0  1  3  3  0  0  0  0  0  0  5  0 36]]
==================================================
Model: Random Forest Classifier
Accuracy: 0.8338001867413632
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.87      0.79        68
           1       0.80      1.00      0.89        72
           2       0.80      0.93      0.86        57
           3       0.86      0.93      0.89        58
           4       0.73      0.36      0.48        66
           5       0.63      0.41      0.50        76
           6       0.90      0.99      0.94        71
           7       0.95      0.95      0.95        61
           8       0.82      1.00      0.90        53
           9       0.69      0.77      0.73        61
          10       0.97      0.97      0.97        63
          11       0.92      0.68      0.78        53
          12       0.89      0.87      0.88        68
          13       0.79      0.98      0.88        55
          14       0.85      0.96      0.90        57
          15       0.86      0.79      0.83        63
          16       0.98      0.83      0.90        69

    accuracy                           0.83      1071
   macro avg       0.83      0.84      0.83      1071
weighted avg       0.83      0.83      0.82      1071

Confusion Matrix:
 [[59  3  0  0  0  2  0  0  1  2  0  1  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 53  0  0  0  2  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0 54  0  0  0  1  0  0  0  0  0  0  3  0  0]
 [ 6  5  6  1 24  9  1  0  2  4  0  1  2  1  1  2  1]
 [ 8  4  0  0  3 31  1  0  5 10  1  1  2  7  0  3  0]
 [ 0  0  0  0  0  0 70  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 58  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0 53  0  0  0  0  0  0  0  0]
 [ 5  0  0  0  0  4  1  0  1 47  0  0  2  0  0  1  0]
 [ 0  0  2  0  0  0  0  0  0  0 61  0  0  0  0  0  0]
 [ 1  2  0  0  3  2  1  0  2  2  0 36  0  2  0  2  0]
 [ 0  1  1  1  1  0  2  0  0  1  1  0 59  1  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  2  0  0  0  0  0  0  0  0  0  0 55  0  0]
 [ 1  2  1  0  2  0  0  0  1  1  0  0  0  3  2 50  0]
 [ 1  0  3  4  0  0  0  2  0  0  0  0  1  0  1  0 57]]
==================================================
Model: K Nearest Neighbors
Accuracy: 0.6834733893557423
Classification Report:
               precision    recall  f1-score   support

           0       0.55      0.60      0.58        68
           1       0.65      0.88      0.75        72
           2       0.68      0.86      0.76        57
           3       0.65      0.88      0.74        58
           4       0.37      0.17      0.23        66
           5       0.41      0.20      0.27        76
           6       0.81      0.94      0.87        71
           7       0.90      0.74      0.81        61
           8       0.63      0.92      0.75        53
           9       0.45      0.39      0.42        61
          10       0.81      0.95      0.88        63
          11       0.71      0.55      0.62        53
          12       0.74      0.78      0.76        68
          13       0.68      0.75      0.71        55
          14       0.80      0.91      0.85        57
          15       0.71      0.67      0.69        63
          16       0.85      0.58      0.69        69

    accuracy                           0.68      1071
   macro avg       0.67      0.69      0.67      1071
weighted avg       0.67      0.68      0.66      1071

Confusion Matrix:
 [[41  4  0  0  0  4  0  0  0  5  8  2  0  1  0  3  0]
 [ 3 63  0  0  0  0  0  0  4  0  0  0  0  2  0  0  0]
 [ 0  0 49  2  0  0  1  0  0  0  0  0  1  0  2  1  1]
 [ 0  0  1 51  0  0  1  1  0  1  0  0  0  1  2  0  0]
 [ 7  9  5  2 11  5  4  1  3  3  1  3  8  0  1  2  1]
 [10  9  0  0  9 15  1  1  5  7  1  2  3  8  1  4  0]
 [ 0  0  1  2  0  0 67  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  3  3  1  0  1 45  0  2  0  1  0  1  2  0  2]
 [ 0  4  0  0  0  0  0  0 49  0  0  0  0  0  0  0  0]
 [ 9  1  2  0  3  6  3  1  3 24  1  1  2  1  1  3  0]
 [ 1  0  1  0  0  0  0  0  0  1 60  0  0  0  0  0  0]
 [ 1  2  0  0  1  5  0  0  3  1  1 29  3  3  0  2  2]
 [ 0  2  5  0  0  0  1  0  2  1  2  0 53  0  0  2  0]
 [ 1  3  0  0  1  2  0  0  2  3  0  1  1 41  0  0  0]
 [ 0  0  1  1  0  0  0  0  0  3  0  0  0  0 52  0  0]
 [ 1  0  0  3  3  0  0  0  7  0  0  2  0  2  2 42  1]
 [ 0  0  4 15  1  0  4  1  0  1  0  0  1  0  2  0 40]]
==================================================
Model: Decision Tree Classifier
Accuracy: 0.6956115779645191
Classification Report:
               precision    recall  f1-score   support

           0       0.63      0.68      0.65        68
           1       0.88      0.83      0.86        72
           2       0.75      0.75      0.75        57
           3       0.81      0.83      0.82        58
           4       0.27      0.23      0.25        66
           5       0.36      0.28      0.31        76
           6       0.86      0.89      0.88        71
           7       0.92      0.79      0.85        61
           8       0.83      0.92      0.88        53
           9       0.52      0.57      0.55        61
          10       0.84      0.92      0.88        63
          11       0.68      0.60      0.64        53
          12       0.66      0.72      0.69        68
          13       0.62      0.76      0.68        55
          14       0.90      0.93      0.91        57
          15       0.55      0.57      0.56        63
          16       0.71      0.68      0.70        69

    accuracy                           0.70      1071
   macro avg       0.69      0.70      0.70      1071
weighted avg       0.69      0.70      0.69      1071

Confusion Matrix:
 [[46  0  0  0  0  7  0  0  2  3  2  3  1  1  0  3  0]
 [ 2 60  0  0  0  4  0  0  1  3  0  0  2  0  0  0  0]
 [ 0  0 43  1  4  0  1  0  0  0  0  0  2  0  0  2  4]
 [ 0  0  0 48  3  0  0  1  0  0  0  0  0  0  3  0  3]
 [ 7  0  4  0 15  8  0  0  2  4  2  3  7  2  0  8  4]
 [ 7  1  0  0 11 21  2  0  1  4  5  6  2  9  0  7  0]
 [ 0  0  2  0  0  1 63  0  0  4  1  0  0  0  0  0  0]
 [ 0  0  0  2  3  0  0 48  0  0  0  0  1  0  1  0  6]
 [ 0  1  0  0  1  0  0  0 49  1  0  1  0  0  0  0  0]
 [ 5  0  0  0  3  5  3  0  1 35  0  0  3  4  0  2  0]
 [ 1  0  0  0  1  0  0  0  0  0 58  0  3  0  0  0  0]
 [ 1  1  1  0  3  4  0  0  1  4  0 32  1  3  0  2  0]
 [ 3  0  3  1  2  4  3  0  0  2  0  0 49  1  0  0  0]
 [ 0  4  0  0  0  2  0  0  0  1  1  1  1 42  0  3  0]
 [ 0  0  0  0  1  0  0  1  0  0  0  0  1  0 53  0  1]
 [ 1  1  0  0  6  3  0  0  2  4  0  1  0  6  2 36  1]
 [ 0  0  4  7  2  0  1  2  0  2  0  0  1  0  0  3 47]]
==================================================
Model: Gaussian Naive Bayes
Accuracy: 0.31559290382819793
Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.22      0.34        68
           1       0.61      0.47      0.53        72
           2       0.22      0.07      0.11        57
           3       0.40      0.10      0.16        58
           4       0.62      0.08      0.14        66
           5       0.47      0.20      0.28        76
           6       0.32      1.00      0.48        71
           7       0.91      0.85      0.88        61
           8       0.56      0.17      0.26        53
           9       0.33      0.05      0.09        61
          10       0.69      0.49      0.57        63
          11       0.71      0.23      0.34        53
          12       0.62      0.15      0.24        68
          13       0.11      0.98      0.20        55
          14       0.33      0.04      0.06        57
          15       0.00      0.00      0.00        63
          16       0.41      0.22      0.28        69

    accuracy                           0.32      1071
   macro avg       0.47      0.31      0.29      1071
weighted avg       0.48      0.32      0.30      1071

Confusion Matrix:
 [[15  0  0  0  0  3  4  0  3  0  4  0  0 39  0  0  0]
 [ 0 34  0  0  0  1  1  0  4  0  0  0  2 30  0  0  0]
 [ 0  0  4  0  0  1 14  0  0  0  2  0  0 31  0  2  3]
 [ 0  0  0  6  0  0 16  1  0  0  0  0  0 19  3  0 13]
 [ 2  2  4  2  5  3  9  0  0  2  1  2  3 29  0  0  2]
 [ 3  6  0  0  0 15 13  0  0  1  0  1  0 36  0  1  0]
 [ 0  0  0  0  0  0 71  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  3 52  0  0  0  0  0  3  1  0  1]
 [ 0  2  0  0  0  1  0  0  9  1  0  0  0 39  0  1  0]
 [ 1  1  0  0  2  2 16  0  0  3  5  0  1 30  0  0  0]
 [ 0  6  0  0  0  0 12  0  0  1 31  0  0 13  0  0  0]
 [ 0  1  0  0  1  1 11  0  0  0  0 12  0 26  0  1  0]
 [ 0  4  4  0  0  0 19  0  0  0  1  0 10 27  0  0  3]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  0  0 12  3  0  0  0  0  0 40  2  0  0]
 [ 0  0  3  0  0  2  5  0  0  1  1  2  0 49  0  0  0]
 [ 0  0  3  6  0  2 19  1  0  0  0  0  0 23  0  0 15]]
==================================================
Model: AdaBoost Classifier
Accuracy: 0.23902894491129786
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        68
           1       1.00      0.62      0.77        72
           2       0.25      0.49      0.33        57
           3       0.00      0.00      0.00        58
           4       0.00      0.00      0.00        66
           5       0.15      0.25      0.19        76
           6       0.28      0.54      0.37        71
           7       0.00      0.00      0.00        61
           8       0.16      1.00      0.27        53
           9       0.00      0.00      0.00        61
          10       0.20      0.14      0.17        63
          11       1.00      0.42      0.59        53
          12       0.00      0.00      0.00        68
          13       0.00      0.00      0.00        55
          14       0.00      0.00      0.00        57
          15       0.00      0.00      0.00        63
          16       0.17      0.61      0.27        69

    accuracy                           0.24      1071
   macro avg       0.19      0.24      0.17      1071
weighted avg       0.19      0.24      0.18      1071

Confusion Matrix:
 [[ 0  0  0  0  0  0  0  0 68  0  0  0  0  0  0  0  0]
 [ 0 45  0  0  0  1  0  0 21  0  5  0  0  0  0  0  0]
 [ 0  0 28  0  0  0 19  0  0  0  0  0  0  0  0  0 10]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 58]
 [ 0  0 10  0  0  9 11  0 27  0  3  0  0  0  0  0  6]
 [ 0  0  0  0  0 19  6  0 45  0  6  0  0  0  0  0  0]
 [ 0  0 21  0  0 12 38  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 61]
 [ 0  0  0  0  0  0  0  0 53  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0 16 12  0 24  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0 12  7  0 35  0  9  0  0  0  0  0  0]
 [ 0  0  0  0  0  9  6  0 13  0  3 22  0  0  0  0  0]
 [ 0  0 16  0  0 12 18  0 11  0  3  0  0  0  0  0  8]
 [ 0  0  1  0  0 17 14  0 19  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 57]
 [ 0  0  8  0  0 18  4  0 25  0  6  0  0  0  0  0  2]
 [ 0  0 27  0  0  0  0  0  0  0  0  0  0  0  0  0 42]]
==================================================
Model: Gradient Boosting Classifier
Accuracy: 0.7366946778711485
Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.79      0.69        68
           1       0.84      0.97      0.90        72
           2       0.62      0.84      0.71        57
           3       0.80      0.84      0.82        58
           4       0.60      0.18      0.28        66
           5       0.47      0.41      0.44        76
           6       0.79      0.97      0.87        71
           7       0.98      0.97      0.98        61
           8       0.74      0.98      0.85        53
           9       0.52      0.43      0.47        61
          10       0.88      0.94      0.91        63
          11       0.88      0.57      0.69        53
          12       0.79      0.68      0.73        68
          13       0.62      0.85      0.72        55
          14       0.84      0.93      0.88        57
          15       0.67      0.48      0.56        63
          16       0.84      0.78      0.81        69

    accuracy                           0.74      1071
   macro avg       0.74      0.74      0.72      1071
weighted avg       0.73      0.74      0.72      1071

Confusion Matrix:
 [[54  2  0  0  0  3  0  0  4  4  1  0  0  0  0  0  0]
 [ 0 70  0  0  0  0  0  0  1  0  0  1  0  0  0  0  0]
 [ 0  0 48  2  0  2  2  0  0  0  2  0  0  0  0  0  1]
 [ 0  0  0 49  1  0  0  1  0  0  0  0  0  0  4  1  2]
 [ 5  3 13  0 12 10  1  0  3  6  0  0  5  3  1  2  2]
 [12  2  0  0  0 31  3  0  1  8  1  0  0 13  0  5  0]
 [ 0  0  1  0  0  0 69  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 59  0  0  0  0  0  0  1  0  0]
 [ 1  0  0  0  0  0  0  0 52  0  0  0  0  0  0  0  0]
 [10  0  2  0  2  7  4  0  2 26  2  1  2  2  0  1  0]
 [ 2  0  0  0  0  1  1  0  0  0 59  0  0  0  0  0  0]
 [ 1  2  0  0  3  3  1  0  3  4  0 30  2  1  0  3  0]
 [ 3  1  2  2  0  0  5  0  1  0  1  0 46  4  0  1  2]
 [ 0  1  2  0  0  1  0  0  1  0  0  1  0 47  0  2  0]
 [ 0  0  1  1  0  0  0  0  0  0  0  0  1  0 53  0  1]
 [ 1  2  5  0  1  8  0  0  2  2  0  1  1  6  2 30  2]
 [ 0  0  4  6  1  0  1  0  0  0  0  0  1  0  2  0 54]]
==================================================
Model: XGBoost Classifier
Accuracy: 0.8216619981325863
Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.85      0.78        68
           1       0.88      0.96      0.92        72
           2       0.80      0.96      0.87        57
           3       0.90      0.93      0.92        58
           4       0.72      0.39      0.51        66
           5       0.49      0.41      0.45        76
           6       0.91      0.99      0.95        71
           7       0.95      0.93      0.94        61
           8       0.88      1.00      0.94        53
           9       0.56      0.66      0.61        61
          10       0.97      0.97      0.97        63
          11       0.86      0.70      0.77        53
          12       0.90      0.88      0.89        68
          13       0.74      0.93      0.82        55
          14       0.92      0.96      0.94        57
          15       0.86      0.67      0.75        63
          16       0.92      0.88      0.90        69

    accuracy                           0.82      1071
   macro avg       0.82      0.83      0.82      1071
weighted avg       0.82      0.82      0.81      1071

Confusion Matrix:
 [[58  1  0  0  0  4  0  0  1  3  0  0  0  1  0  0  0]
 [ 1 69  0  0  0  0  0  0  0  0  0  0  1  0  0  1  0]
 [ 0  0 55  0  0  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 54  1  0  0  1  0  0  0  0  0  0  2  0  0]
 [ 4  4  6  0 26  7  1  0  1  8  0  1  2  2  1  2  1]
 [ 9  2  0  0  4 31  2  0  2 12  1  2  0 10  0  1  0]
 [ 0  0  0  0  0  0 70  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0 57  0  0  0  0  0  0  1  0  1]
 [ 0  0  0  0  0  0  0  0 53  0  0  0  0  0  0  0  0]
 [ 4  0  2  0  0  8  1  0  1 40  1  2  1  0  0  1  0]
 [ 2  0  0  0  0  0  0  0  0  0 61  0  0  0  0  0  0]
 [ 1  1  0  0  0  4  1  0  2  5  0 37  2  0  0  0  0]
 [ 1  0  0  1  1  0  1  0  0  0  0  0 60  2  0  1  1]
 [ 0  0  1  0  0  1  0  0  0  1  0  0  0 51  0  1  0]
 [ 0  0  0  1  0  0  0  1  0  0  0  0  0  0 55  0  0]
 [ 0  1  3  0  1  7  0  0  0  1  0  1  1  3  1 42  2]
 [ 0  0  2  2  3  0  0  1  0  0  0  0  0  0  0  0 61]]

# Random Forest

In [26]:
model=RandomForestClassifier()
model.fit(X_train_scaled ,y_train)

y_pred=model.predict(X_test_scaled)

print("Accuracy: " ,accuracy_score(y_test ,y_pred))
print("report: ",classification_report(y_test,y_pred))
print("Confusion Matrix: " ,confusion_matrix(y_test,y_pred))

Accuracy:  0.838468720821662
report:                precision    recall  f1-score   support

           0       0.71      0.88      0.79        68
           1       0.78      1.00      0.88        72
           2       0.84      0.91      0.87        57
           3       0.86      0.93      0.89        58
           4       0.80      0.42      0.55        66
           5       0.67      0.32      0.43        76
           6       0.89      0.99      0.93        71
           7       0.97      0.95      0.96        61
           8       0.85      1.00      0.92        53
           9       0.63      0.77      0.69        61
          10       0.97      1.00      0.98        63
          11       0.95      0.75      0.84        53
          12       0.91      0.88      0.90        68
          13       0.79      0.96      0.87        55
          14       0.86      0.98      0.92        57
          15       0.88      0.79      0.83        63
          16       0.95      0.84      0.89        69

    accuracy                           0.84      1071
   macro avg       0.84      0.85      0.83      1071
weighted avg       0.84      0.84      0.83      1071

Confusion Matrix:  [[60  4  0  0  1  0  0  0  0  2  0  1  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 52  1  0  0  1  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0 54  0  0  0  1  0  0  0  0  0  0  3  0  0]
 [ 5  4  6  0 28  4  1  0  2  6  0  1  2  1  1  4  1]
 [11  7  0  0  1 24  1  0  4 14  1  0  2  9  0  2  0]
 [ 0  0  0  0  0  0 70  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 58  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0 53  0  0  0  0  0  0  0  0]
 [ 5  1  0  0  0  3  3  0  0 47  0  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 63  0  0  0  0  0  0]
 [ 1  2  0  0  2  3  1  0  2  1  0 40  0  0  0  1  0]
 [ 0  1  1  1  1  0  2  0  0  1  1  0 60  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  1  0  0  0 53  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0 56  0  0]
 [ 1  0  0  0  2  1  0  0  1  2  0  0  0  4  2 50  0]
 [ 1  0  3  5  0  0  0  1  0  0  0  0  0  0  1  0 58]]

# single input prediction

In [27]:
print("Predicted Labele:", model.predict(X_test_scaled[10].reshape(1,-1)))
print("Actual:",y_test.iloc[10])

Predicted Labele: [12]
Actual: 12

In [28]:
print("Predicted Labele:", model.predict(X_test_scaled[4].reshape(1,-1)))
print("Actual:",y_test.iloc[4])

Predicted Labele: [4]
Actual: 4

In [29]:
print("Predicted Labele:", model.predict(X_test_scaled[100].reshape(1,-1)))
print("Actual:",y_test.iloc[100])

Predicted Labele: [12]
Actual: 12

In [30]:
print("Predicted Labele:", model.predict(X_test_scaled[55].reshape(1,-1)))
print("Actual:",y_test.iloc[55])

Predicted Labele: [10]
Actual: 10

In [31]:
print("Predicted Labele:", model.predict(X_test_scaled[1001].reshape(1,-1)))
print("Actual:",y_test.iloc[1001])

Predicted Labele: [0]
Actual: 0

In [32]:
y_test.iloc[10]

12

# Saving and Loading File

In [33]:
import pickle
pickle.dump(scaler,open("Models/scaler.pkl",'wb'))
pickle.dump(model,open("Models/model.pkl",'wb'))

In [34]:
scaler=pickle.load(open("Models/scaler.pkl",'rb'))
model=pickle.load(open("Models/model.pkl",'rb'))

# Recommendation system

In [35]:
import pickle
import numpy as np

# Load the scaler, label encoder, model, and class names
scaler = pickle.load(open("Models/scaler.pkl", 'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))
class_names = ['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
               'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
               'Banker', 'Writer', 'Accountant', 'Designer',
               'Construction Engineer', 'Game Developer', 'Stock Investor',
               'Real Estate Developer']

def Recommendations(gender, part_time_job, absence_days, extracurricular_activities,
                    weekly_self_study_hours, math_score, history_score, physics_score,
                    chemistry_score, biology_score, english_score, geography_score,
                    total_score,average_score):
    
    # Encode categorical variables
    gender_encoded = 1 if gender.lower() == 'female' else 0
    part_time_job_encoded = 1 if part_time_job else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0
    
    # Create feature array
    feature_array = np.array([[gender_encoded, part_time_job_encoded, absence_days, extracurricular_activities_encoded,
                               weekly_self_study_hours, math_score, history_score, physics_score,
                               chemistry_score, biology_score, english_score, geography_score,total_score,average_score]])
    
    # Scale features
    scaled_features = scaler.transform(feature_array)
    
    # Predict using the model
    probabilities = model.predict_proba(scaled_features)
    
    # Get top five predicted classes along with their probabilities
    top_classes_idx = np.argsort(-probabilities[0])[:5]
    top_classes_names_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]
    
    return top_classes_names_probs

In [36]:
# example 1
final_recommendations = Recommendations(gender='female',
                                        part_time_job=False,
                                        absence_days=2,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=7,
                                        math_score=65,
                                        history_score=60,
                                        physics_score=97,
                                        chemistry_score=94,
                                        biology_score=71,
                                        english_score=81,
                                        geography_score=66,
                                        total_score=534,
                                        average_score=76.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
==================================================
Teacher with probability 0.31
Writer with probability 0.12
Real Estate Developer with probability 0.09
Construction Engineer with probability 0.07
Designer with probability 0.06

In [37]:
# example 2
final_recommendations = Recommendations(gender='female',
                                        part_time_job=False,
                                        absence_days=2,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=4,
                                        math_score=87,
                                        history_score=73,
                                        physics_score=98,
                                        chemistry_score=91,
                                        biology_score=79,
                                        english_score=60,
                                        geography_score=77,
                                        total_score=583,
                                        average_score=83.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
==================================================
Artist with probability 0.34
Game Developer with probability 0.23
Doctor with probability 0.13
Real Estate Developer with probability 0.06
Lawyer with probability 0.05

In [38]:
# sklear version in pychar production 
import sklearn
print(sklearn.__version__)
# in pycharm env install
# pip install scikit-learn==1.3.2

1.4.1.post1